#we need to create a production docker file

FROM node:22.17-alpine as builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:22.17-alpine as production
ENV NODE_ENV=production
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev --ignore-scripts
COPY --from=builder /usr/src/app/dist ./
COPY --from=builder /usr/src/app/src/certs ./src/certs
EXPOSE 8080
CMD ["node", "src/server.js"]