sonar.projectKey=Kishan0145_auth-service
sonar.organization=kishan0145
sonar.sources=src
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/coverage/**, **/tests/**, **/*.spec.ts, **/*.test.ts, **/*.d.ts
